config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', 
  confirmation: 'verification', registration: 'register', sign_up: 'sign_up' } 

  resources :clients
  resources :orders
  resources :dishes
  resources :users

  scope module: :api, path: "api" do
    resources :clients
    resources :dishes
    resources :orders
    resources :users
    resources :sessions, only: [:create]
    resources :orders, only: [:create]
    resources :sessions_client, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "dashboards#index"
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :orders
    enum status_client: { active: 0, inactive: 1}
end

app/controllers/api/clients_controller.rb
module Api 
  class ClientsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_client, only: %i[ show edit update destroy ]

    def index
      @clients = Client.all
    end

    def show
    end

    def new
      @client = Client.new
    end

    def edit
    end

    def create
      @client = Client.new(client_params)


        if @client.save
          render 'api/clients/show', status: :created
        else
          render json: @client.errors, status: :unprocessable_entity
        end
      
    end

    def update

        if @client.update(client_params)
          render 'api/clients/show', status: :created
        else
          render json: @client.errors, status: :unprocessable_entity
        end
      
    end

    def destroy
      @client.destroy

        render 'api/clients/index', status: :ok
    end
  

    private
      def set_client
        @client = Client.find(params[:id])
      end

      def client_params
        params.require(:client).permit(:client_name, :email, :client_password, :direction, :status_client)
      end      
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]
  before_action :authenticate_user! 
  include UserAdministratorTypeAuthorization

  def index
    @clients = Client.all
  end

  def show; end

  def new
    @client = Client.new
  end

  def edit; end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to client_url(@client), notice: t('activerecord.attributes.client.client_created') 
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def update
    if @client.update(client_params)
      redirect_to client_url(@client), notice: t('activerecord.attributes.client.client_updated') 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_url, notice: t('activerecord.attributes.client.client_destroyed')
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:client_name, :email, :client_password, :direction, :status_client)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
    def status_clients
        Client.status_clients.keys.map do |status_client|
            [t("activerecord.attributes.user.types.#{status_client}"), status_client]
        end
    end
end

app/views/clients/_client.html.haml
.container.mt-4
  %h1 
    = t('activerecord.modules.client.one')
  %div{:id => "#{dom_id client}", :style => "background-color: #f5f5f5; padding: 10px; border: 1px solid #ccc; margin-bottom: 10px;"}
    %p{:style => "background-color: #f5f5f5; padding: 10px; border: 1px solid #ccc; margin-bottom: 10px;"}
      %strong 
        = t('activerecord.attributes.client.client_name')
        =" : "
      = client.client_name
    %p{:style => "background-color: #f5f5f5; padding: 10px; border: 1px solid #ccc; margin-bottom: 10px;"}
      %strong 
        = t('activerecord.attributes.client.email')
        =" : "
      = client.email
    %p{:style => "background-color: #f5f5f5; padding: 10px; border: 1px solid #ccc; margin-bottom: 10px;"}
      %strong 
        = t('activerecord.attributes.client.client_password')
        =" : "
      = client.client_password
    %p{:style => "background-color: #f5f5f5; padding: 10px; border: 1px solid #ccc; margin-bottom: 10px;"}
      %strong 
        = t('activerecord.attributes.client.direction')
        =" : "
      = client.direction
  %div
    = link_to t('activerecord.attributes.client.back_to_clients'), clients_path, style: "display: inline-block; padding: 0.5rem 1rem; background-color: #6c757d; color: #fff; text-decoration: none; border-radius: 0.25rem; border: none;"
    |
    = link_to t('application.edit'), edit_client_path(@client), class: "btn btn-success"
    
    = button_to t('application.delete'), @client, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"

app/views/clients/_form.html.haml
.container.mt-4
  = form_with(model: client) do |form|
    - if client.errors.any?
      %div{:style => "color: red"}
        %h2
          = pluralize(client.errors.count, "error")
          prohibited this client from being saved:
        %ul
          - client.errors.each do |error|
            %li= error.full_message
    %div
      = form.label :client_name, style: "display: block"
      = form.text_field :client_name, class: "form-control"
    %div
      = form.label :email, style: "display: block"
      = form.text_field :email, class: "form-control"
    %div
      = form.label :client_password, style: "display: block"
      = form.text_field :client_password, class: "form-control"
    %div
      = form.label :direction, style: "display: block"
      = form.text_field :direction, class: "form-control"
    .form-group.ml-4.mr-4
      = form.label t('activerecord.attributes.client.status'), class: 'form-label required'
      = form.select(:status_client, options_for_select(status_clients, @client.status_client),
    {prompt:"Seleccione"}, class:'form-control')
    .form-group
      = form.submit t('application.save'), class: "btn btn-primary"
    %div
      = link_to t('activerecord.attributes.client.back_to_clients'), clients_path, style: "display: inline-block; padding: 0.5rem 1rem; background-color: #6c757d; color: #fff; text-decoration: none; border-radius: 0.25rem; border: none;"

app/views/clients/edit.html.haml
.container
  %h1 
    = t('application.edit_model', model: t('activerecord.modules.client.one'))
  = render "form", client: @client

app/views/clients/index.html.haml
#clients.container.mt-4
  .div.m-4.my-4.py-4
    .page.header
      %h1.mb-4
        %p{:style => "color: green"}= notice
        = t('application.list_of', model: t('activerecord.modules.client.other'))
      .float-end.pb-4
        = link_to t('application.new_model', model: t('activerecord.modules.client.one')), new_client_path, class: "btn btn-primary"
  %table.table.table-striped
    %thead
      %tr
        %th= t('activerecord.attributes.client.id')
        %th= t('activerecord.attributes.client.name')
        %th= t('activerecord.attributes.client.email')
        %th= t('activerecord.attributes.client.direction')
        %th= t('activerecord.attributes.client.status')
        %th
    %tbody
      - @clients.each do |client|
        %tr
          %td= client.id
          %td= client.client_name
          %td= client.email
          %td= client.direction
          %td= client.status_client
          %td
          %td= link_to t('application.show', model: t('activerecord.modules.client.one')), client, class: "btn btn-info"
          %td= link_to t('application.edit'), edit_client_path(client), class: "btn btn-success"
          %td= button_to t('application.delete'), client, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"
  %div
    = link_to t('activerecord.attributes.client.back_to_clients'), root_path, style: "display: inline-block; padding: 0.5rem 1rem; background-color: #6c757d; color: #fff; text-decoration: none; border-radius: 0.25rem; border: none;"

app/views/clients/new.html.haml
.container 
  %h1 
    = t('application.new_model', model: t('activerecord.modules.client.one'))
  = render "form", client: @client

app/views/clients/show.html.haml
%p{:style => "color: green"}= notice
= render @client
  