config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', 
  confirmation: 'verification', registration: 'register', sign_up: 'sign_up' } 

  resources :clients
  resources :orders
  resources :dishes
  resources :users

  scope module: :api, path: "api" do
    resources :clients
    resources :dishes
    resources :orders
    resources :users
    resources :sessions, only: [:create]
    resources :orders, only: [:create]
    resources :sessions_client, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "dashboards#index"
end

app/models/dish.rb
class Dish < ApplicationRecord
    has_many :orders
    has_one_attached :picture
    has_rich_text :description
    enum status_dish: { active: 0, inactive: 1}
end

app/controllers/api/dishes_controller.rb
module Api 
    class DishesController < ApplicationController
      skip_before_action :verify_authenticity_token
      before_action :set_plate, only: %i[ show edit update destroy ]
  
      def index
        @dishes = Dish.where(status_dish: 'active')
      end
  
      def show
      end
  
      def new
        @dish =  Dish.new
      end
  
      def edit
      end
  
      def create
        @dish =  Dish.new(dish_params)
  
  
          if @dish.save
            render 'api/dishes/show', status: :created
          else
            render json: @dish.errors, status: :unprocessable_entity
          end
        
      end
  
      def update
        if @dish.update(dish_params)
          render 'api/dishes/show', status: :ok, location: @dish
        else
          render json: @dish.errors, status: :unprocessable_entity
        end
      end
  
      def destroy
        @dish.destroy
  
          render 'api/dishes/index', status: :ok
      end
    
  
      private
        def set_plate
          @dish =  Dish.find(params[:id])
        end
  
        def dish_params
            params.require(:dish).permit(:name, :description, :price, :picture, :status_dish, :order_id)
        end
    end
  end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[ show edit update destroy ]
  before_action :authenticate_user! 
  include UserAdministratorTypeAuthorization

  def index
    ActiveStorage::Current.url_options = Rails.application.config.action_mailer.default_url_options
    @dishes = Dish.all
  end

  def show; end

  def new
    @dish = Dish.new
  end

  def edit; end

  def create
    @dish = Dish.new(dish_params)
    if @dish.save
      redirect_to dish_url(@dish), notice: t('activerecord.attributes.dish.dish_created')
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def update
    if @dish.update(dish_params)
      redirect_to dish_url(@dish), notice: t('activerecord.attributes.dish.dish_updated') 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @dish.destroy
    redirect_to dishes_url, notice: t('activerecord.attributes.dish.dish_destroyed') 
  end

  private
    def set_dish
      @dish = Dish.find(params[:id])
    end

    def dish_params
      params.require(:dish).permit(:name, :description, :price, :picture, :status_dish, :order_id)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
    def status_dishes
      Dish.status_dishes.keys.map do |status_dish|
        [t("activerecord.attributes.dish.status_dishes.#{status_dish}"), status_dish]
      end
    end
end
  

app/views/dishes/_dish.html.haml
.container.mt-4
  %div{:id => "#{dom_id dish}"}
    %p{:style => "background-color: #f5f5f5; padding: 10px; border: 1px solid #ccc; margin-bottom: 10px;"}
      %strong
        = t('activerecord.attributes.dish.name')
        =" : "
      = dish.name

    %p{:style => "background-color: #f5f5f5; padding: 10px; border: 1px solid #ccc; margin-bottom: 10px;"}
      %strong
        = t('activerecord.attributes.dish.description')
        =" : "
      = dish.description
    %p{:style => "background-color: #f5f5f5; padding: 10px; border: 1px solid #ccc; margin-bottom: 10px;"}
      %strong
        = t('activerecord.attributes.dish.price')
        =" : "
      = dish.price
    %p
      %strong 
        = t('activerecord.attributes.dish.picture')
        =" : "
      - if dish.picture.present?
        = image_tag dish.picture, width: 200
      - else
        No picture available

app/views/dishes/_form.html.haml
= form_with(model: dish) do |f|
  - if dish.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(dish.errors.count, "error")
        prohibited this dish from being saved:
      %ul
        - dish.errors.each do |error|
          %li= error.full_message
  %div
    = f.label :name, style: "display: block"
    = f.text_field :name, class: "form-control"
  %div
    = f.label :description, style: "display: block"
    = f.text_area :description, value: strip_tags(f.object.description.body.to_s), class: "form-control"
  %div
    = f.label :price, style: "display: block"
    = f.number_field :price, class: "form-control"
  %div
    = f.label :picture, style: "display: block"
    = f.file_field :picture, class: "form-control"
  .form-group.ml-4.mr-4
    = f.label t('activerecord.attributes.dish.status'), class: 'form-label required'
    = f.select(:status_dish, options_for_select(status_dishes, @dish.status_dish), {prompt: t('application.select')}, class:'form-control')
  .form-group
    = f.submit t('application.save'), class: "btn btn-primary"
  %div
    = link_to t('activerecord.attributes.dish.back_to_dishes'), dishes_path, style: "display: inline-block; padding: 0.5rem 1rem; background-color: #6c757d; color: #fff; text-decoration: none; border-radius: 0.25rem; border: none;"

app/views/dishes/edit.html.haml
.container
  %h1.Editing-dish 
    = t('application.edit_model', model: t('activerecord.modules.dish.one'))
  = render "form", dish: @dish

app/views/dishes/index.html.haml
.container.mt-4
  .div.m-4.my-4.py-4
    .page.header
      %h1.mb-4
        %p{:style => "color: green"}= notice
        = t('application.list_of', model: t('activerecord.modules.dish.other'))
      .float-end.pb-4
        = link_to t('application.new_model', model: t('activerecord.modules.dish.one')), new_dish_path, class: "btn btn-primary"
    %table.table.table-striped
      %thead
        %tr
          %th= t('activerecord.attributes.dish.name')
          %th= t('activerecord.attributes.dish.description')
          %th= t('activerecord.attributes.dish.price')
          %th= t('activerecord.attributes.dish.picture')
      %tbody
        - @dishes.each do |dish|
          %tr
            %td= dish.name
            %td= dish.description
            %td= dish.price
            %td
              - if dish.picture.present?
                = image_tag dish.picture.url, class: "dish-picture", style: "width: 200px; height: 100px;"
              - else
                No picture available
            %td= link_to t('application.show', model: t('activerecord.modules.dish.one')), dish, class: "btn btn-info"
            %td= link_to t('application.edit'), edit_dish_path(dish), class: "btn btn-success"
            %td= button_to t('application.delete'), dish, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"
    %div
      = link_to t('application.back_to_menu'), root_path, style: "display: inline-block; padding: 0.5rem 1rem; background-color: #6c757d; color: #fff; text-decoration: none; border-radius: 0.25rem; border: none;"

app/views/dishes/new.html.haml
.container
  %h1.New-dish 
    = t('application.new_model', model: t('activerecord.modules.dish.one'))
  = render "form", dish: @dish

app/views/dishes/show.html.haml
.container
  %h1.Editing-dish 
    %p{:style => "color: green"}= notice
    = t('activerecord.modules.dish.one')
    
  = render @dish
  %div
    = link_to t('activerecord.attributes.dish.back_to_dishes'), dishes_path, style: "display: inline-block; padding: 0.5rem 1rem; background-color: #6c757d; color: #fff; text-decoration: none; border-radius: 0.25rem; border: none;"
    |
    = link_to t('application.edit'), edit_dish_path(@dish), class: " btn btn-success"
    |
    = button_to t('application.delete'), @dish, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"