config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', 
  confirmation: 'verification', registration: 'register', sign_up: 'sign_up' } 

  resources :clients
  resources :orders
  resources :dishes
  resources :users

  scope module: :api, path: "api" do
    resources :clients
    resources :dishes
    resources :orders
    resources :users
    resources :sessions, only: [:create]
    resources :orders, only: [:create]
    resources :sessions_client, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "dashboards#index"
end

app/controllers/concerns/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index; end

end

app/views/dashboards/index.html.haml
.div.container.text-center.mt-5
  %h1.mb-4
    = t('activerecord.attributes.dashboard.main_menu')

.div.container.text-center.mt-5
  .div.d-flex.justify-content-center.my-4
    = link_to t('activerecord.modules.dish.other'), dishes_path, class: 'btn btn-info btn-lg mx-2'

    = link_to t('activerecord.modules.user.other'), users_path, class: 'btn btn-info btn-lg mx-2'

    = link_to t('activerecord.modules.client.other'), clients_path, class: 'btn btn-info btn-lg mx-2'

    = link_to t('activerecord.modules.order.other'), orders_path, class: 'btn btn-info btn-lg mx-2'

    = button_to t('activerecord.attributes.dashboard.log_off'), destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-lg mx-2'